### ISSUE TITLE
Error loading config: open /var/task/datadog.yaml: no such file or directory

### ISSUE THREAD

**Issue by RomanMinkin** [DataDog/serverless-plugin-datadog#183]
## Expected Behavior
No warning message appears should appear in the log 

## Actual Behavior
Following warning appears in the log on every Lambda Function invocation:
```
SAGENT | WARN | Error loading config: open /var/task/datadog.yaml: no such file or directory
```

## Steps to Reproduce the Problem

  1. Have `serverless-plugin-datadog` used by the lambda function
  1. Invoke Function
  1. The warning shows up in the log

## Specifications

  - Serverless Framework version: 1.74.1
  - Datadog Serverless Plugin version: 2.34.1, 3.1.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs12.x
  
## Stacktrace
  No stack trace

**Comment by astuyve** [comment]
Hi @RomanMinkin!
This appears to be coming from the datadog agent, which would mean you're using the Datadog Lambda Extension, correct?

Is the environment variable `DD_LOG_LEVEL` set? If so, what is it set to?

This appears [intentional](https://github.com/DataDog/datadog-agent/blob/7aff44df2936a84e392979bbae4e74c19707336a/pkg/config/config.go#L1101), but I don't think it should be shown for every invocation unless `DD_LOG_LEVEL` is set.

Let me know!

**Comment by astuyve** [comment]
@RomanMinkin Yup, even an empty one would work.

**Comment by astuyve** [comment]
Oh - the plugin won't create it for you. You can just run `touch datadog.yaml` to create an empty file in your project, then when you run `severless deploy`, the Serverless Framework will automatically package it up and inject the empty file into your runtime. This will suppress the error (since the file exists, but contains no configuration). Then you can keep `DD_LOG_LEVEL: INFO` and won't see the message.
