### ISSUE TITLE
How to completely remove serverless-plugin-datadog and stop forwarding logs to datadog?

### ISSUE THREAD

**Issue by sweeetland** [DataDog/serverless-plugin-datadog#272]
## Expected Behavior
I have uninstalled the package. And in `serverless.yml` I have removed `serverless-plugin-datadog` from `plugins` and the configuration object `custom.datadog`. Then I have deployed the service. I would expect that logs would no longer be forwarded to datadog but that is not the case.

## Actual Behavior
We are still seeing logs in datadog!

## Specifications

  - Serverless Framework version: `3.12.0`
  - Datadog Serverless Plugin version:  was `^4.3.0` ... now it is uninstalled.
  - Lambda function runtime: `Nodejs16.x`

**Comment by astuyve** [comment]
Hi, if you're using the [Datadog Forwarder](https://docs.datadoghq.com/logs/guide/forwarder/) removing this library isn't sufficient because the log groups from your lambda functions are subscribed to the forwarder itself. You'll need remove those via CloudWatch, or using the [Datadog CI](https://github.com/DataDog/datadog-ci) `uninstrument` command.

**Comment by astuyve** [comment]
Closing as there's been no reply, please feel free to re-open with a reply. Thanks!
