### ISSUE TITLE
Some logs dont have trace attributes

### ISSUE THREAD

**Issue by Ugikie** [DataDog/serverless-plugin-datadog#306]
## Expected Behavior
Expecting to see all of the dd trace attributes (env, host, version, etc.) and other information on logs as seen in the screenshot below:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/22334248/196769543-b2f4c1f8-f790-4982-a546-71f469ca958c.png">

## Actual Behavior
Occasionally, some logs will come in from the exact same service, and exact same function, but with no attributes, as seen in this screenshot:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/22334248/196769868-1cd4ac61-accb-412b-878f-c6d603f7c43e.png">

## Steps to Reproduce the Problem

  1. Create a lambda function using serverless and the serverless-plugin-datadog, following [these instructions](https://docs.datadoghq.com/serverless/installation/nodejs/?tab=serverlessframework)
  1. Call the lambda function
  1. See if the logs produce the same results as in the screenshots? (not really sure how to reproduce this)

## Specifications

 - Framework Core: 3.21.0
 - Plugin: 6.2.2
 - SDK: 4.3.2
 - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs16.x
  
## Stacktrace
  
  ```
  N/A
  ```

To provide some more context on this issue, basically what I am seeing is that some of the logs coming from lambda, mainly the automatic ones that say `START RequestId: ...` that happen when the lambda is first called. Rarely, but seemingly once or twice a day, these logs come in with no attributes at all. Not even host or env. If you look closely at the timestamps in the logs however, you will notice that they happen just 9 minutes apart. The log that correctly has all the attributes came in first, and then for some reason, 9 minutes later, the exact same type of log from the exact same lambda function running in the exact same service came in with no attributes. Even `arn` and `hostname` are blank, which to me seems weird.

The other logs that came in from the 2nd call to the lambda had all the attributes, but its just this first log that has the `START RequestId` in it... is there any way to just disable those logs?

Thanks in advance and sorry if this was not the right place to post this issue

**Comment by purple4reina** [comment]
Hey @Ugikie, thanks for opening this issue. We're aware of the problem, are tracking it internally, and are actively looking for a solution.

You are correct that some logs created just after a function is deployed for the first time are missing important tags. This happens because these logs are created before we receive the first invocation event and therefore we do not yet know the `function_arn`. As a consequence, initialization logs aren’t presented correctly in our UI.

If you'd like, we encourage you to open a [support ticket](https://help.datadoghq.com/hc/en-us/requests/new). This will make it easy to assist you on your specific use case and reach back out once we've implemented a fix.

**Comment by astuyve** [comment]
Hi, this should now be fixed with version [36](https://github.com/DataDog/datadog-lambda-extension/releases/tag/v36) of the Datadog Extension, and was addressed in this [pr](https://github.com/DataDog/datadog-agent/pull/14207).

Please feel free to re-open if there are other issues, thanks!
