### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by sylvainv** [DataDog/serverless-plugin-datadog#308]
## Expected Behavior

* https://docs.datadoghq.com/serverless/libraries_integrations/plugin/
* https://github.com/DataDog/serverless-plugin-datadog
* https://www.npmjs.com/package/serverless-plugin-datadog

* `subscribeToAccessLogs` and `subscribeToExecutionLogs` should be documented and `subscribeToApiGatewayLogs` marked as deprecated.
* `addExtension` is marked as "Whether to install the Datadog Lambda Extension as a layer. Defaults to true. When enabled, it’s required to set the apiKey and site" But it seems unrelated and has influence on whether log subscriptions are set.

## Actual Behavior

For `subscribeToAccessLogs` and `subscribeToExecutionLogs`
```
Error: The following configuration options have been removed: subscribeToApiGatewayLogs. Please use the subscribeToAccessLogs or subscribeToExecutionLogs options instead.
```

For `addExtension` set to `true`, then lambda logs subscriptions are not set, no message is returned regarding this. Setting `addExtension` to `false` sets the log subscription correctly (provided the deployer role has the necessary permissions).

## Specifications

  - Serverless Framework version: 3.22.0
  - Datadog Serverless Plugin version: 5.9.0

**Comment by astuyve** [comment]
Hi @sylvainv thanks for pointing these out. A quick note:
- `addExtension` uses the datadog lambda extension to ship logs, metrics, and traces asynchronously to Datadog. The extension runs alongside a lambda function, and therefore has no access to access logs created by API Gateway (v1/v2/websocket).

I don't think it's relevant to call that out in the `addExtension` section because the fact that the forwarder is required to forward logs from non-lambda resources is covered in the `subscribeToAccessLogs` and `subscribeToExecutionLogs` description (wherein `fowardeArn` is required).

I'll deprecate the other two.
