### ISSUE TITLE
Monitor variable interpolating doesn't work

### ISSUE THREAD

**Issue by rdsedmundo** [DataDog/serverless-plugin-datadog#326]
## Expected Behavior
Timeout on some-function-name in us-east-1 for 312894198

## Actual Behavior
Timeout on {{functionname.name}} in {{region.name}} for {{aws_account.name}}

## Steps to Reproduce the Problem

  1. Create a `timeout` monitor using the default configurations.

## Specifications

  - Serverless Framework version: 3.22.0
  - Datadog Serverless Plugin version: 5.13.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 16
  
## Stacktrace
  
N/A.

Monitor ID is 105448046 if that's helpful.

**Comment by sfirrin** [comment]
Hi @rdsedmundo, thanks for getting in touch

The monitor name showing as `Timeout on {{functionname.name}} in {{region.name}} for {{aws_account.name}}` in the UI is expected. We have the template variables in the name so that whichever Lambda function is getting timeouts will be reflected in the alert name. When the monitor alerts, the alert notification will replace the variable strings with the name / region / account of the Lambda function with timeouts, and the title of the resulting alert should be `Timeout on some-function-name in us-east-1 for 312894198` as expected. We have this doc with some info about attribute and tag variables in monitors https://docs.datadoghq.com/monitors/notify/variables/?tab=is_alert#attribute-and-tag-variables.

**Comment by rdsedmundo** [comment]
Ah ok, thanks for the clarifying.
