### ISSUE TITLE
Lambda Layer size issues

### ISSUE THREAD

**Issue by Gabe1203** [DataDog/serverless-plugin-datadog#368]
## Expected Behavior
We have a series of microservices that use lambda layers for the python requirements needed. We also use this Datadog plugin to enable Datadog on our services. Has worked as expected until last week.

## Actual Behavior
Recently our deployments failed because the combined lambda layer size was too large. We made no changes to any of our requirement layer. Upon further investigation it seems that the newest Datadog serverless plugin update pushed us over our lambda layer size limit. When we deploy our services we do this using github actions and we install the latest version of this plugin each time. 

We've temporarily solved this problem by pinning the plugin version to 5.20.1 and the deployment works as expected. This is a fine solution for now but we would like to be able to update the plugin version without having to worry about going over the lambda layer size restrictions. 

We have a few questions based on this:
1. Is the increase in size of the Datadog layers with the update of the plugin from 5.20.1 -> 5.21.0 expected to increase the size of the Datadog layers?
2. Is there any recommended solutions as to how we may still use this plugin even if the size of its layers increase in the futures? 

## Steps to Reproduce the Problem
Can't provide the exact configurations we have here but if more information on our set up is helpful I can provide some. 

## Specifications

  - Serverless Framework version: 5.21.0
  - Datadog Serverless Plugin version: Latest (3.29.0)
  - Lambda function runtime (Python 3.7, Node 10, etc.): Python3.9
  
## Stacktrace
  
  ```
  Layers consume more than the available size of 262144000 bytes
  ```

Thanks for any help!

**Comment by astuyve** [comment]
Hi @Gabe1203 - thanks for the note!

The size of the python [lambda layer](https://github.com/DataDog/datadog-lambda-python) is tracked (both zipped and unzipped) as a ci/cd check. That size limit is 7mb compressed and 24mb uncompressed. [Here's the source](https://github.com/DataDog/datadog-lambda-python/blob/main/scripts/check_layer_size.sh#L10-L12).

If you're using the Datadog Lambda Extension, that also counts towards the layer limit and today is around 30mb.

You can verify the size of the specific layer versions you're using the steps described [here](https://docs.datadoghq.com/serverless/guide/serverless_package_too_large/).

For 5.21.0, those versions are [here](https://github.com/DataDog/serverless-plugin-datadog/blob/v5.21.0/src/layers.json).

One thing I'd suggest verifying is that this library is installed as a devDependency, not a service dependency. This can occur because the Serverless Framework plugin system is based on NPM, and occasionally that mistake is made.

Please let me know if you've verified this. The next steps would be to remove this plugin and run `sls package`, then determine the current size of your application and if the math all checks out (which would rule out a packaging issue).

Thanks!

**Comment by Gabe1203** [comment]
@astuyve Thanks so much for such a quick answer! 

So upon further investigation it seems like the issue was our requirements layer was large enough that even a slight increase in the Datadog layer size caused our total layer size to go over the limit. We have been able to solve this by slimming that requirements layer. Decreased from 206 mb unzipped to 189 mb unzipped (still large but it deploys now). 

Out of curiosity - is there a way to use the python lambda layer and not the datadog lambda extension? 

Thanks again for your help with this!

**Comment by astuyve** [comment]
Hey @Gabe1203 - thanks for that context, it's quite helpful!

Bumping up against the 250mb limit is unfortunately common. You may want to verify that you're not packaging unneeded, heavy dependencies (like boto3), or other development-only dependencies (test runners, etc).

From there, you could also use a docker-based Lambda function to increase the deployment size to 10gb.

Additionally you could break your function up into smaller, specialized functions - especially if it's a monolith-lambda (or lambda-lith) API.

If those options are untenable, you can use the older [Datadog lambda forwarder](https://docs.datadoghq.com/logs/guide/forwarder/) to forward logs, metrics, and traces from your Lambda functions. But generally we do not recommend using the forwarder, as some features are not available with that option, and the forwarder is more costly as it incurs additional CloudWatchLogs charges.

Please do let me know if you have other questions.
Thanks!

**Comment by Gabe1203** [comment]
Thanks for even more info - really appreciate the advice and help with this! Going to mark the issue as closed now since we got it all sorted and have a great day!
