### ISSUE TITLE
[Question] Does the plugin support Datadog APM/tracing?

### ISSUE THREAD

**Issue by pramttl** [DataDog/serverless-plugin-datadog#5]
Per documentation it seems like the plugin supports auto-magic addition of Lambda layers to functions pre-req to metrics instrumentation.  Just wondering if it also supports APM/tracing for lambda functions? 

My use case has a lot of lambda timeout errors and I would like to investigate/understand bottlenecks by integrating APM/tracing into the serverless app/lambda handlers.

**Comment by pinkerton** [comment]
Hi @pramttl, the Lambda Layers enable distributed tracing across serverless functions (using X-Ray) and host-based infrastructure (using Datadog APM). It ensures that the tracing headers are propagated correctly so that Datadog can stitch together the traces.

The Serverless Framework plugin automatically enables X-Ray for your Lambda and API Gateway resources. The only step you need to do in order to get full tracing _within_ your functions is to install the corresponding X-Ray client library.

I see you work for GoodRx - would you mind if I reach out over email? We have a few things in the works that we'd love to give you early access to!

**Comment by pramttl** [comment]
@pinkerton sure, pranjal<at>goodrx<com>. GoodRx already uses Datadog extensively and we love it. 

The serverless-datadog-plugin is of interest to us. The other thing that I was curious about in reference to tracing is, if it also supports tracing spans within lambda handlers to measure time spent in a specific subset/span of statements within a lambda function (I mean, not just tracing the entire lambda function and external calls it makes but inner spans too).

**Comment by sfirrin** [comment]
Hey @pramttl, sorry for the delay in getting back to you.

>The other thing that I was curious about in reference to tracing is, if it also supports tracing spans within lambda handlers to measure time spent in a specific subset/span of statements within a lambda function?

Yes, we're collecting any subsegments your handler produces with X-Ray and using those to create the spans in the Datadog APM trace. [The AWS docs here](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-subsegments.html) explain how to record custom X-Ray subsegments in your Lambda handler.

If you're using Node you can also try out our [beta Datadog tracer](https://github.com/DataDog/datadog-lambda-layer-js#datadog-tracer-experimental), which uses the Datadog tracing library to record APM spans either independently of or working together with X-Ray.
