### ISSUE TITLE
Bump `@datadog/datadog-ci` version to at least v2.38.0 to avoid vulnerability in ws < 7.5.10

### ISSUE THREAD

**Issue by holzerch** [DataDog/serverless-plugin-datadog#501]
`ws` in version < 7.5.10 has a vulnerability. 
Please upgrade your dependency of `@datadog/datadog-ci` to at least version v2.38.0 to no longer pull an affected version

**Comment by astuyve** [comment]
This should be fixed in [5.68.0](https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.68.0)

**Comment by holzerch** [comment]
@astuyve could you please reopen the ticket? The problem was not solved by the latest release. The old version is still used. https://github.com/DataDog/serverless-plugin-datadog/blob/ddc507a35e219ce936ea5365eeaba16e901136f7/package.json#L60

**Comment by astuyve** [comment]
Hi @holzerch,
Even though I didn't explicitly bump the dependency on datadog-ci, the caret dependency insures that the last release used `@datadog/datadog-ci` at [2.41.0](https://github.com/DataDog/serverless-plugin-datadog/blob/main/yarn.lock#L952) which includes [ws at ^7.5.10](https://github.com/DataDog/serverless-plugin-datadog/blob/main/yarn.lock#L999).

I tried installing this package in a new project, using `5.69.0` and confirmed it installs `ws` @ `7.5.10` which should be the patched version:
<img width="622" alt="image" src="https://github.com/user-attachments/assets/d4069216-de40-459a-ab55-549c2bae327c">

Is there a chance your module cache is resolve to 2.32.0 anyway? I'm not sure how you're specifically testing this. Maybe clear your node modules and remove the `package-lock.json` file and try installing this library at 2.68.0+ and try again?

Thanks!
AJ

**Comment by holzerch** [comment]
The screenshot above comes from Github Dependabot, so it cannot be a local issue. I think your local lib build uses now an updated version of `@datadog/datadog-ci` however since the package.json declares the old version, on our side still the old version is pulled.

**Comment by astuyve** [comment]
Hi @holzerch thanks for the reply. I'm sorry my rambling 2am post wasn't helpful, I was trying to soothe my newborn.

I think there's some confusion as to how lockfiles and semantic versioning works.

This:
> So I think updating your yarn.lock has no impact for the users of your lib

Is totally true. A `package-lock.json` file is only for collaborators in a project, eg other developers pulling this repository and working on it. It ensures that we all get the exact same node modules within this package. When a package is pushed to npm/yarn's registries, only the `package.json` file is uploaded. (You can verify this by browsing the [package contents](https://www.npmjs.com/package/serverless-plugin-datadog?activeTab=code))

This part, however, is not correct:
> however since the package.json declares the old version, on our side still the old version is pulled.

The fact that your project (or dependabot) pulls in `@datadog/datadog-ci@2.32.0` instead of `2.41.0` is a misconfiguration of some kind, unless you explicitly depend on this version elsewhere.

A `package.json` file specifies the *permanent constraints* of a dependency. In some cases that's a hard-pin (eg `foo=1.2.3` would only ever allow foo@1.2.3). But in this case, our dependency on `@datadog/datadog-ci` is a caret dependency.

We do not declare nor require an old version, we simply specify the minimum compatible version for our needs. [Here](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004) is a good overview of how that works.

This means this library will permit `@datadog/datadog-ci`'s 2.32.0 release, and anything above within the 2.x major version line. This includes the latest 2.41.0 release, which in turn specifies the patched version of `ws@7.5.10`.

In fact there was no need for this github issue, or an update for this library to begin with – as you could always bring in the patched version of this specific dependency. Semver ranges are designed this way intentionally because it would be madness if every single library had to manually bump every single version of every possible dependency (and their dependencies, and their dependencies, and so on).

But I often run `npm upgrade` to satisfy these types of requests (see also #509). As I've already demonstrated, NPM will happily install the latest versions of this libraries dependencies, so I don't think that's the issue here.

I'm not sure how your project is structured, but my earlier advice remains the same. Please regenerate your `package-lock.json` file in your project with `npm update` or `yarn upgrade` (or the equivalent in whatever package manager you choose). If that doesn't satisfy dependabot, you may need to configure dependabot's `versioning-strategy` to use `increasing` instead of `widen`, which is [documented in this excellent stackoverflow answer](https://stackoverflow.com/questions/60201543/dependabot-only-updates-lock-file).

I hope this explanation is helpful, thanks again!
AJ

**Comment by holzerch** [comment]
Thank for your detailed explanation and congratulations to your newborn @astuyve ! `npm update` indeed helped
