### ISSUE TITLE
AWS Lambda with Node.js 22 runtime

### ISSUE THREAD

**Issue by mblumenstingl-n11** [DataDog/serverless-plugin-datadog#559]
## Expected Behavior
AWS Lambdas using the `nodejs22.x` runtime work in the same way as the ones using runtime `nodejs20.x`

## Actual Behavior
Warning/error messages are logged during the build:
```
...
Auto instrumenting functions with Datadog
Adding Lambda Library Layers to functions
Unable to add Lambda Layers to function our-function-name-redacted with runtime nodejs22.x
Adding Datadog Lambda Extension Layer to functions
Unable to add Lambda Layers to function our-function-name-redacted with runtime nodejs22.x
Adding Datadog Env Vars
Adding Plugin Version 5.74.0 tag
Adding source code integration
Uploading git metadata
...
```
Additionally no requests to the lambda show up in Datadog after the deployment.

## Steps to Reproduce the Problem
  1. Deploy a lambda with runtime `nodejs22.x`

## Specifications

  - Serverless Framework version: 3.39.0
  - Datadog Serverless Plugin version: 5.74.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 22
  
Node 22 is officially supported by AWS since a few days: https://aws.amazon.com/blogs/compute/node-js-22-runtime-now-available-in-aws-lambda/
I could not find any info about it on the `serverless-plugin-datadog` roadmap.
For reference, Node 20 support has been added with fdee48d54c63aaace3eff3b4cc99d90790a978fe

**Comment by lym953** [comment]
Thanks for the request and the reference. I'll look into it.

By the way, due to a production freeze, we won't be able to support it within two weeks. Also, we just released the [Lambda layer for Node 22](https://github.com/DataDog/datadog-lambda-js/pull/595) and supported it in [CDK](https://github.com/DataDog/datadog-cdk-constructs). If you want it sooner, you can try manual setup or use CDK instead of Serverless Plugin.

**Comment by sras3584** [comment]
@lym953  when will you release this change in production?

**Comment by lym953** [comment]
@sras3584 Done! Thanks for the reminder.
