### ISSUE TITLE
Not able to see the service map of lambda interactions for serverless

### ISSUE THREAD

**Issue by bala1074** [DataDog/serverless-plugin-datadog#78]
Missing details in service map.
1. Lambda trigger traces, lambda was trigger periodically by cloudwatch event(every 1minute)
2. Lambda is communicating with DynamoDB to fetch result

In service map, I am getting only function, no other interactions.

![dd](https://user-images.githubusercontent.com/12669425/97699907-f0c69d00-1ad0-11eb-8183-fbc042c23a9f.png)

**Comment by bala1074** [comment]
why datadog serverless is not providing support for multiple lambda triggers?

**Comment by tianchu** [comment]
@bala1074 Again, sorry for the late reply here! Recently we did release a feature to show the exact AWS resource that triggers each Lambda invocation in the Datadog serverless function page. Currently, the triggering service doesn't show up in the service map, because there isn't a way for AWS-managed services (CloudWatch, SNS, etc.) to emit a span to Datadog. However, we are working on an improvement to **infer** the trigger information from the `event` payload and use that to generate a span for the trigger (which would show up in service map). Stay tuned.

Thank you for your feedback! It helps us to know what we are building is going to be useful! Really appreciate!

**Comment by tianchu** [comment]
Closing. AWS managed services are now better represented in Datadog APM, see https://www.datadoghq.com/blog/monitor-aws-fully-managed-services-datadog-serverless-monitoring/
