### ISSUE TITLE
Lambda trace logs appearing in CloudWatch/Datadog logs

### ISSUE THREAD

**Issue by IcyWednesdays** [DataDog/serverless-plugin-datadog#93]
Hi there!

We're currently seeing trace logs for our serverless Lambda functions emitted into CloudWatch/Datadog logs alongside 'real' logs for our functions. This is resulting in huge log volume, most of which is trace information that is of no interest and makes it harder to access real logs. Note that traces *are working* for our functions, so we don't want to interfere with that, we just want to prevent the trace information making it into logs. We've isolated this issue to something with this library as the unwanted logs are present in CloudWatch as well as Datadog, so the log forwarder function is working as expected.

### Function details
**Runtime:** nodejs12.x
**Serverless framework version:** 1.83.0
**Serverless Datadog plugin version:** 1.1.0

<details>
<summary>An example trace log</summary>
<br>

```
{
    "traces": [
        [
            {
                "trace_id": "xxx",
                "span_id": "xxx",
                "parent_id": "xxx",
                "name": "aws.lambda",
                "resource": "handler",
                "error": 0,
                "meta": {
                    "service": "my-function",
                    "cold_start": "false",
                    "function_arn": "arn:aws:lambda:us-east-1:012345678910:function:my-function",
                    "function_version": "$LATEST",
                    "request_id": "xxx",
                    "resource_names": "my-function",
                    "language": "javascript"
                },
                "metrics": {
                    "_sample_rate": 1,
                    "_sampling_priority_v1": 2
                },
                "start": 1608589168898002000,
                "duration": 10888428,
                "service": "my-function",
                "type": "serverless"
            }
        ]
    ]
}
```
</details>

We don't do much manual instrumentation of our functions for tracing or logging, we mainly rely on the `serverless-plugin-datadog` library with the following config:

```
  datadog:
    addLayers: true
    apiKey: xxx
    flushMetricsToLogs: true
    enableTags: true
    forwarder: <datadog-log-forwarder function>
```

### What we've tried

So far we've tried the following on one of our functions currently logging trace information:

- Setting `enableDDTracing = false`: this stopped all logging, including real logs
- Setting `injectLogContext = false`: this made no difference

Any guidance you can give us on why this might be happening and how we could fix it is greatly appreciated. Let me know if you need any more information from our side.

**Comment by agocs** [comment]
Generally speaking, the best way to get support on issues like these is to go through support@datadog.com. Then they know which company you work for and can check configuration in your datadog instance. 

However, the first thing I would check is the subscriptions on your lambda function's log group (Go into Cloudwatch, search for the log group, and subscriptions will be displayed in the rightmost column I think.). Make sure it's just one subscription, and that it's pointing to the forwarder you configured above.

Simultaneously, go into Datadog, and check the AWS Integration tile (Integrations > Amazon Web Services > Collect Logs). Find the appropriate AWS account and then check on the `Currently Used Lambda ARNs`. The Forwarder lambda function should match one of those ARNs.

Also check the version of the forwarder function. There's a chance it might not handle traces correctly if it was super old (couldn't hurt to upgrade it to the latest just to be sure).

Finally, the last thing I would try, just diagnostically, would be setting `flushMetricsToLogs: false`, and adding the `DD_API_KEY` and `DD_SITE` env vars. Normally, your traces and metrics are written to logs, and those get picked up by the forwarder function. The forwarder should be able to recognize metrics and traces and submit them to the appropriate endpoint rather than the logs endpoint. By disabling flushMetricsToLogs, we can force the Lambda library to send metrics and traces directly to Datadog, circumventing logs. https://github.com/DataDog/datadog-lambda-js#dd_flush_to_log

**Comment by IcyWednesdays** [comment]
@agocs Thanks very much for your prompt and thorough response! We'll give these steps a crack and let you know how we go 👍

**Comment by agocs** [comment]
Oh yeah, one more thing. Just to clarify, with `flushMetricsToLogs: true`, it is expected that you'd see traces in the Cloudwatch logs. It's unexpected that they're in the Datadog logs.

**Comment by IcyWednesdays** [comment]
@agocs We ended up resolving this thanks to your advice. It turned out we were running a very back-levelled version of the plugin, and since moving to the latest version have seen the trace logs disappear.

Thanks again for your help with this, much appreciated!
